name: Pipeline

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop, 'release/**', 'feature/**', 'hotfix/**' ]
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      publish_target:
        description: 'Publish target'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - testpypi
          - pypi

jobs:
  ci:
    uses: ITlusions/ITL.Github/.github/workflows/_reusable-python-ci.yml@v0.2.16
    with:
      python_version: '3.12'
      test_import_path: 'itl_braincell_sdk.core.config'
      test_import_class: 'Settings'
      src_directory: 'src'

  publish:
    uses: ITlusions/ITL.Github/.github/workflows/_reusable-python-publish.yml@v0.2.5
    if: |
      github.event_name == 'release' ||
      startsWith(github.ref, 'refs/heads/feature/') ||
      startsWith(github.ref, 'refs/heads/hotfix/')
    needs: [ ci ]
    with:
      python_version: '3.12'
      testpypi_url: 'https://test.pypi.org/legacy/'
      pypi_url: 'https://upload.pypi.org/legacy/'
    secrets: inherit
