name: Publish - Release

on:
  release:
    types: [ published ]
  push:
    branches: [ 'feature/**', 'hotfix/**' ]
  workflow_dispatch:
    inputs:
      publish_target:
        description: 'Publish target'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - testpypi
          - pypi

jobs:
  publish:
    uses: ./.github/workflows/publish.template.yml
    with:
      python_version: '3.12'
      testpypi_url: 'https://test.pypi.org/legacy/'
      pypi_url: 'https://upload.pypi.org/legacy/'
    secrets: inherit
